// @ts-check

const { sidebarsConfig } = require('./apis');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    'welcome',

    {
      type: 'category',
      label: 'Standard Operating Procdures',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sops',
        },
      ],
    },
    {
      type: 'category',
      label: 'Discord',
      items: [
        {
          type: 'autogenerated',
          dirName: 'discord',
        },
      ],
    },
    {
      type: 'category',
      label: 'Dev Resources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dev-help',
        },
      ],
    },
  ],

  ...sidebarsConfig,
};

module.exports = sidebars;
